name: clang-build-and-test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        compiler: [gcc, clang]

    env:
      BUILD_TYPE: Release

    steps:
    - uses: actions/checkout@main

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install ninja-build cmake
        sudo apt install clang libc++-dev libc++abi-dev

    - name: Set up compiler
      run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

    - name: Configure with CMake
      run: cmake -S . -B build -G "Ninja Multi-Config" build -DFIBER_COMPILE_TESTS=ON -DFIBER_CTEST=ON

    - name: Build
      run: cmake --build build --config Release

    - name: Run CTest
      run: ctest --test-dir build -C Release -V
